#!/usr/bin/env bash

java -jar compiler.jar                         \
	--language_in ECMASCRIPT_2015              \
	--language_out ECMASCRIPT5                 \
	--js js/Matrix/Cells.js                    \
	--js js/Matrix/Model.js                    \
	--compilation_level ADVANCED               \
	--js_output_file js/out/matrix.adv.min.js